# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xc8GnHS-Yna1dCmh39HocKz-V053i1Lc
"""

#Movie ticket platform
logins = {}
import random

#Save logins
try:
    file = open("logins.txt", "r")
    for x in file:
        Username, Password = x.strip().split(",")
        logins[Username] = Password
    file.close()

except FileNotFoundError:
    pass


# Signup
def sign():
    Username = input("Create a username: ")
    while True:
        if Username in logins:
            print("\nERROR: Username entered is exsisting in the database already\n")
            Username = input("Create a username: ")

        else:
            Password = input("Enter a password: ")
            Recheck = input("Re-enter your password: ")

            if Password == Recheck:
                logins[Username] = Password
                file = open("logins.txt", "a")
                file.write(f"{Username},{Password}\n")
                file.close()
                print("\nAccount created\n")
                break

            else:
                print("\nERROR: Passwords do not match\n")


# Login
def login():
    Username = input("Enter your username: ")

    if Username not in logins:
        print("\nERROR: Username not found in database\n")
        print("Redirecting to signup...\n")
        sign()
        login()
        return

    while True:
        User_PW = input("Enter your password: ")

        if logins[Username] == User_PW:
            print("\n--------Welcome to SilverFrame Cinemas--------\n")
            break

        else:
            print("\nERROR: Incorrect password\n")

#Main Movie Menu
Total = 0
Seats_Total = 100

Movie_Seats = {
    1: random.randint(20, 100),
    2: random.randint(20, 100),
    3: random.randint(20, 100)}

Booked_Seats = {
    1: 0,
    2: 0,
    3: 0}

Movie_Names = {
    1: "PROJECT Hail Mary",
    2: "The Mandalorian & Grogu",
    3: "Michael"}

Movie_Prices = {
    1: 1300,
    2: 1450,
    3: 1600}


def show_movies():
    print("===========================================================================")

    print("\n1. PROJECT Hail Mary - Big sci-fi adventure with Ryan Gosling   --Rs.1300")
    print("Seats available:", Movie_Seats[1], "out of 100\n")
    print("===========================================================================")

    print("\n2. The Mandalorian & Grogu — Star Wars movie   --Rs.1450")
    print("Seats available:", Movie_Seats[2], "out of 100\n")
    print("===========================================================================")

    print("\n3. Michael — based on Michael Jackson   --Rs.1600")
    print("Seats available:", Movie_Seats[3], "out of 100\n")
    print("===========================================================================")


def book_ticket():
    global Total
    while True:

        Choice = int(input("\nEnter the movie number you want to watch: "))

        if Choice not in Movie_Seats:
            print("\nERROR Invalid choice\n")
            continue

        Num_Tickets = int(input("Enter number of tickets: "))

        if Num_Tickets > Movie_Seats[Choice]:
            print("\nERROR: Not enough seats available for this movie\n")
            continue

        if Choice == 1:
            Total += Num_Tickets * 1300

        elif Choice == 2:
            Total += Num_Tickets * 1450

        elif Choice == 3:
            Total += Num_Tickets * 1600

        Movie_Seats[Choice] -= Num_Tickets
        Booked_Seats[Choice] += Num_Tickets

        print("\n------------------------------")
        print("Tickets booked successfully!")
        print("Seats booked for this movie:", Booked_Seats[Choice])
        print("------------------------------\n")

        more = input("\nDo you want to book more tickets? (yes/no): ").lower()

        if more == "no":
            break

        elif more != "yes":
            print("\nERROR Invalid choice\n")


def Summary():
  print("")
  print("\n-----Booking Summary-----\n")

  for i in Movie_Names:
      if Booked_Seats[i] > 0:
        movie_total = Booked_Seats[i] * Movie_Prices[i]
        print(Movie_Names[i])
        print("Seats booked:", Booked_Seats[i])
        print("Total price: Rs.", movie_total)
        print("-------------------------")




# Main Program
print("\n-----SilverFrame Cinemas-----\n")

while True:
    User_Choice = input("Do you want to signup or login? ").lower()

    if User_Choice == "signup":
        sign()
        login()
        break

    elif User_Choice == "login":
        login()
        break

    else:
        print("\nERROR: Invalid choice\n")
show_movies()
book_ticket()


Summary()
# Billing
print("\n---Bill---\n")
print("Total price for tickets: Rs.", Total)
print("Net total with tax: Rs.", Total + 200)

print("\n---Thank you for buying tickets at SilverFrame Cinemas---\n")

